#[derive(Debug, PartialEq, Eq, Hash, Clone, Copy)]
#[allow(non_camel_case_types, dead_code)]
pub enum Keys {
    Unknown,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,
    KEY_ZENKAKUHANKAKU,
    KEY_102ND,
    KEY_F11,
    KEY_F12,
    KEY_RO,
    KEY_KATAKANA,
    KEY_HIRAGANA,
    KEY_HENKAN,
    KEY_KATAKANAHIRAGANA,
    KEY_MUHENKAN,
    KEY_KPJPCOMMA,
    KEY_KPENTER,
    KEY_RIGHTCTRL,
    KEY_KPSLASH,
    KEY_SYSRQ,
    KEY_RIGHTALT,
    KEY_LINEFEED,
    KEY_HOME,
    KEY_UP,
    KEY_PAGEUP,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_MACRO,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_POWER,/* SC System Power Down */
    KEY_KPEQUAL,
    KEY_KPPLUSMINUS,
    KEY_PAUSE,
    KEY_SCALE,	/* AL Compiz Scale (Expose) */
    KEY_KPCOMMA,
    KEY_HANGEUL,
    KEY_HANJA,
    KEY_YEN,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_COMPOSE,

    KEY_STOP,/* AC Stop */
    KEY_AGAIN,
    KEY_PROPS,/* AC Properties */
    KEY_UNDO,/* AC Undo */
    KEY_FRONT,
    KEY_COPY,/* AC Copy */
    KEY_OPEN,/* AC Open */
    KEY_PASTE,/* AC Paste */
    KEY_FIND,/* AC Search */
    KEY_CUT,/* AC Cut */
    KEY_HELP,/* AL Integrated Help Center */
    KEY_MENU,/* Menu (show menu) */
    KEY_CALC,/* AL Calculator */
    KEY_SETUP,
    KEY_SLEEP,/* SC System Sleep */
    KEY_WAKEUP,/* System Wake Up */
    KEY_FILE,/* AL Local Machine Browser */
    KEY_SENDFILE,
    KEY_DELETEFILE,
    KEY_XFER,
    KEY_PROG1,
    KEY_PROG2,
    KEY_WWW,/* AL Internet Browser */
    KEY_MSDOS,
    KEY_COFFEE,/* AL Terminal Lock/Screensaver */
    KEY_SCREENLOCK,
    KEY_ROTATE_DISPLAY,/* Display orientation for e.g. tablets */
    KEY_DIRECTION,
    KEY_CYCLEWINDOWS,
    KEY_MAIL,
    KEY_BOOKMARKS,/* AC Bookmarks */
    KEY_COMPUTER,
    KEY_BACK,/* AC Back */
    KEY_FORWARD,/* AC Forward */
    KEY_CLOSECD,
    KEY_EJECTCD,
    KEY_EJECTCLOSECD,
    KEY_NEXTSONG,
    KEY_PLAYPAUSE,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
    KEY_RECORD,
    KEY_REWIND,
    KEY_PHONE,/* Media Select Telephone */
    KEY_ISO,
    KEY_CONFIG,/* AL Consumer Control Configuration */
    KEY_HOMEPAGE,/* AC Home */
    KEY_REFRESH,/* AC Refresh */
    KEY_EXIT,/* AC Exit */
    KEY_MOVE,
    KEY_EDIT,
    KEY_SCROLLUP,
    KEY_SCROLLDOWN,
    KEY_KPLEFTPAREN,
    KEY_KPRIGHTPAREN,
    KEY_NEW,/* AC New */
    KEY_REDO,	/* AC Redo/Repeat */
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,
    KEY_PLAYCD,
    KEY_PAUSECD,
    KEY_PROG3,
    KEY_PROG4,
    KEY_DASHBOARD,	/* AL Dashboard */
    KEY_SUSPEND,
    KEY_CLOSE,	/* AC Close */
    KEY_PLAY,
    KEY_FASTFORWARD,
    KEY_BASSBOOST,
    KEY_PRINT,/* AC Print */
    KEY_HP,
    KEY_CAMERA,
    KEY_SOUND,
    KEY_QUESTION,
    KEY_EMAIL,
    KEY_CHAT,
    KEY_SEARCH,
    KEY_CONNECT,
    KEY_FINANCE,/* AL Checkbook/Finance */
    KEY_SPORT,
    KEY_SHOP,
    KEY_ALTERASE,
    KEY_CANCEL,/* AC Cancel */
    KEY_BRIGHTNESSDOWN,
    KEY_BRIGHTNESSUP,
    KEY_MEDIA,
    KEY_SWITCHVIDEOMODE,/* Cycle between available video outputs (Monitor/LCD/TV-out/etc) */
    KEY_KBDILLUMTOGGLE,
    KEY_KBDILLUMDOWN,
    KEY_KBDILLUMUP,
    KEY_SEND,	/* AC Send */
    KEY_REPLY,	/* AC Reply */
    KEY_FORWARDMAIL,/* AC Forward Msg */
    KEY_SAVE,/* AC Save */
    KEY_DOCUMENTS,
    KEY_BATTERY,
    KEY_BLUETOOTH,
    KEY_WLAN,
    KEY_UWB,
    KEY_VIDEO_NEXT,/* drive next video source */
    KEY_VIDEO_PREV,/* drive previous video source */
    KEY_BRIGHTNESS_CYCLE,/* brightness up, after max is min */
    KEY_BRIGHTNESS_AUTO,/* Set Auto Brightness: manual brightness control is off, rely on ambient */
    KEY_BRIGHTNESS_ZERO,
    KEY_DISPLAY_OFF,/* display device to off state */
    KEY_WWAN,	/* Wireless WAN (LTE, UMTS, GSM, etc.) */
    KEY_WIMAX,
    KEY_RFKILL,	/* Key that controls all radios */
    KEY_MICMUTE
}

impl Keys {
    #![allow(dead_code)]
    pub fn from_code(code : u16) -> Keys{
        match code {
            1 => Keys::KEY_ESC,
            2 => Keys::KEY_1,
            3 => Keys::KEY_2,
            4 => Keys::KEY_3,
            5 => Keys::KEY_4,
            6 => Keys::KEY_5,
            7 => Keys::KEY_6,
            8 => Keys::KEY_7,
            9 => Keys::KEY_8,
            10 => Keys::KEY_9,
            11 => Keys::KEY_0,
            12 => Keys::KEY_MINUS,
            13 => Keys::KEY_EQUAL,
            14 => Keys::KEY_BACKSPACE,
            15 => Keys::KEY_TAB,
            16 => Keys::KEY_Q,
            17 => Keys::KEY_W,
            18 => Keys::KEY_E,
            19 => Keys::KEY_R,
            20 => Keys::KEY_T,
            21 => Keys::KEY_Y,
            22 => Keys::KEY_U,
            23 => Keys::KEY_I,
            24 => Keys::KEY_O,
            25 => Keys::KEY_P,
            26 => Keys::KEY_LEFTBRACE,
            27 => Keys::KEY_RIGHTBRACE,
            28 => Keys::KEY_ENTER,
            29 => Keys::KEY_LEFTCTRL,
            30 => Keys::KEY_A,
            31 => Keys::KEY_S,
            32 => Keys::KEY_D,
            33 => Keys::KEY_F,
            34 => Keys::KEY_G,
            35 => Keys::KEY_H,
            36 => Keys::KEY_J,
            37 => Keys::KEY_K,
            38 => Keys::KEY_L,
            39 => Keys::KEY_SEMICOLON,
            40 => Keys::KEY_APOSTROPHE,
            41 => Keys::KEY_GRAVE,
            42 => Keys::KEY_LEFTSHIFT,
            43 => Keys::KEY_BACKSLASH,
            44 => Keys::KEY_Z,
            45 => Keys::KEY_X,
            46 => Keys::KEY_C,
            47 => Keys::KEY_V,
            48 => Keys::KEY_B,
            49 => Keys::KEY_N,
            50 => Keys::KEY_M,
            51 => Keys::KEY_COMMA,
            52 => Keys::KEY_DOT,
            53 => Keys::KEY_SLASH,
            54 => Keys::KEY_RIGHTSHIFT,
            55 => Keys::KEY_KPASTERISK,
            56 => Keys::KEY_LEFTALT,
            57 => Keys::KEY_SPACE,
            58 => Keys::KEY_CAPSLOCK,
            59 => Keys::KEY_F1,
            60 => Keys::KEY_F2,
            61 => Keys::KEY_F3,
            62 => Keys::KEY_F4,
            63 => Keys::KEY_F5,
            64 => Keys::KEY_F6,
            65 => Keys::KEY_F7,
            66 => Keys::KEY_F8,
            67 => Keys::KEY_F9,
            68 => Keys::KEY_F10,
            69 => Keys::KEY_NUMLOCK,
            70 => Keys::KEY_SCROLLLOCK,
            71 => Keys::KEY_KP7,
            72 => Keys::KEY_KP8,
            73 => Keys::KEY_KP9,
            74 => Keys::KEY_KPMINUS,
            75 => Keys::KEY_KP4,
            76 => Keys::KEY_KP5,
            77 => Keys::KEY_KP6,
            78 => Keys::KEY_KPPLUS,
            79 => Keys::KEY_KP1,
            80 => Keys::KEY_KP2,
            81 => Keys::KEY_KP3,
            82 => Keys::KEY_KP0,
            83 => Keys::KEY_KPDOT,
            85 => Keys::KEY_ZENKAKUHANKAKU,
            86 => Keys::KEY_102ND,
            87 => Keys::KEY_F11,
            88 => Keys::KEY_F12,
            89 => Keys::KEY_RO,
            90 => Keys::KEY_KATAKANA,
            91 => Keys::KEY_HIRAGANA,
            92 => Keys::KEY_HENKAN,
            93 => Keys::KEY_KATAKANAHIRAGANA,
            94 => Keys::KEY_MUHENKAN,
            95 => Keys::KEY_KPJPCOMMA,
            96 => Keys::KEY_KPENTER,
            97 => Keys::KEY_RIGHTCTRL,
            98 => Keys::KEY_KPSLASH,
            99 => Keys::KEY_SYSRQ,
            100 => Keys::KEY_RIGHTALT,
            101 => Keys::KEY_LINEFEED,
            102 => Keys::KEY_HOME,
            103 => Keys::KEY_UP,
            104 => Keys::KEY_PAGEUP,
            105 => Keys::KEY_LEFT,
            106 => Keys::KEY_RIGHT,
            107 => Keys::KEY_END,
            108 => Keys::KEY_DOWN,
            109 => Keys::KEY_PAGEDOWN,
            110 => Keys::KEY_INSERT,
            111 => Keys::KEY_DELETE,
            112 => Keys::KEY_MACRO,
            113 => Keys::KEY_MUTE,
            114 => Keys::KEY_VOLUMEDOWN,
            115 => Keys::KEY_VOLUMEUP,
            116 => Keys::KEY_POWER,
            117 => Keys::KEY_KPEQUAL,
            118 => Keys::KEY_KPPLUSMINUS,
            119 => Keys::KEY_PAUSE,
            120 => Keys::KEY_SCALE,
            121 => Keys::KEY_KPCOMMA,
            122 => Keys::KEY_HANGEUL,
            123 => Keys::KEY_HANJA,
            124 => Keys::KEY_YEN,
            125 => Keys::KEY_LEFTMETA,
            126 => Keys::KEY_RIGHTMETA,
            127 => Keys::KEY_COMPOSE,
            128 => Keys::KEY_STOP,
            129 => Keys::KEY_AGAIN,
            130 => Keys::KEY_PROPS,
            131 => Keys::KEY_UNDO,
            132 => Keys::KEY_FRONT,
            133 => Keys::KEY_COPY,
            134 => Keys::KEY_OPEN,
            135 => Keys::KEY_PASTE,
            136 => Keys::KEY_FIND,
            137 => Keys::KEY_CUT,
            138 => Keys::KEY_HELP,
            139 => Keys::KEY_MENU,
            140 => Keys::KEY_CALC,
            141 => Keys::KEY_SETUP,
            142 => Keys::KEY_SLEEP,
            143 => Keys::KEY_WAKEUP,
            144 => Keys::KEY_FILE,
            145 => Keys::KEY_SENDFILE,
            146 => Keys::KEY_DELETEFILE,
            147 => Keys::KEY_XFER,
            148 => Keys::KEY_PROG1,
            149 => Keys::KEY_PROG2,
            150 => Keys::KEY_WWW,
            151 => Keys::KEY_MSDOS,
            152 => Keys::KEY_COFFEE,
            153 => Keys::KEY_ROTATE_DISPLAY,
            154 => Keys::KEY_CYCLEWINDOWS,
            155 => Keys::KEY_MAIL,
            156 => Keys::KEY_BOOKMARKS,
            157 => Keys::KEY_COMPUTER,
            158 => Keys::KEY_BACK,
            159 => Keys::KEY_FORWARD,
            160 => Keys::KEY_CLOSECD,
            161 => Keys::KEY_EJECTCD,
            162 => Keys::KEY_EJECTCLOSECD,
            163 => Keys::KEY_NEXTSONG,
            164 => Keys::KEY_PLAYPAUSE,
            165 => Keys::KEY_PREVIOUSSONG,
            166 => Keys::KEY_STOPCD,
            167 => Keys::KEY_RECORD,
            168 => Keys::KEY_REWIND,
            169 => Keys::KEY_PHONE,
            170 => Keys::KEY_ISO,
            171 => Keys::KEY_CONFIG,
            172 => Keys::KEY_HOMEPAGE,
            173 => Keys::KEY_REFRESH,
            174 => Keys::KEY_EXIT,
            175 => Keys::KEY_MOVE,
            176 => Keys::KEY_EDIT,
            177 => Keys::KEY_SCROLLUP,
            178 => Keys::KEY_SCROLLDOWN,
            179 => Keys::KEY_KPLEFTPAREN,
            180 => Keys::KEY_KPRIGHTPAREN,
            181 => Keys::KEY_NEW,
            182 => Keys::KEY_REDO,
            183 => Keys::KEY_F13,
            184 => Keys::KEY_F14,
            185 => Keys::KEY_F15,
            186 => Keys::KEY_F16,
            187 => Keys::KEY_F17,
            188 => Keys::KEY_F18,
            189 => Keys::KEY_F19,
            190 => Keys::KEY_F20,
            191 => Keys::KEY_F21,
            192 => Keys::KEY_F22,
            193 => Keys::KEY_F23,
            194 => Keys::KEY_F24,
            200 => Keys::KEY_PLAYCD,
            201 => Keys::KEY_PAUSECD,
            202 => Keys::KEY_PROG3,
            203 => Keys::KEY_PROG4,
            204 => Keys::KEY_DASHBOARD,
            205 => Keys::KEY_SUSPEND,
            206 => Keys::KEY_CLOSE,
            207 => Keys::KEY_PLAY,
            208 => Keys::KEY_FASTFORWARD,
            209 => Keys::KEY_BASSBOOST,
            210 => Keys::KEY_PRINT,
            211 => Keys::KEY_HP,
            212 => Keys::KEY_CAMERA,
            213 => Keys::KEY_SOUND,
            214 => Keys::KEY_QUESTION,
            215 => Keys::KEY_EMAIL,
            216 => Keys::KEY_CHAT,
            217 => Keys::KEY_SEARCH,
            218 => Keys::KEY_CONNECT,
            219 => Keys::KEY_FINANCE,
            220 => Keys::KEY_SPORT,
            221 => Keys::KEY_SHOP,
            222 => Keys::KEY_ALTERASE,
            223 => Keys::KEY_CANCEL,
            224 => Keys::KEY_BRIGHTNESSDOWN,
            225 => Keys::KEY_BRIGHTNESSUP,
            226 => Keys::KEY_MEDIA,
            227 => Keys::KEY_SWITCHVIDEOMODE,
            228 => Keys::KEY_KBDILLUMTOGGLE,
            229 => Keys::KEY_KBDILLUMDOWN,
            230 => Keys::KEY_KBDILLUMUP,
            231 => Keys::KEY_SEND,
            232 => Keys::KEY_REPLY,
            233 => Keys::KEY_FORWARDMAIL,
            234 => Keys::KEY_SAVE,
            235 => Keys::KEY_DOCUMENTS,
            236 => Keys::KEY_BATTERY,
            237 => Keys::KEY_BLUETOOTH,
            238 => Keys::KEY_WLAN,
            239 => Keys::KEY_UWB,
            241 => Keys::KEY_VIDEO_NEXT,
            242 => Keys::KEY_VIDEO_PREV,
            243 => Keys::KEY_BRIGHTNESS_CYCLE,
            244 => Keys::KEY_BRIGHTNESS_AUTO,
            245 => Keys::KEY_DISPLAY_OFF,
            246 => Keys::KEY_WWAN,
            247 => Keys::KEY_RFKILL,
            248 => Keys::KEY_MICMUTE,
            _ => Keys::Unknown
        }
    }
    #[allow(dead_code)]
    pub fn into_code(key: Keys) -> u16{
        match key {
            Keys::Unknown => 0,
            Keys::KEY_ESC => 1,
            Keys::KEY_1 => 2,
            Keys::KEY_2 => 3,
            Keys::KEY_3 => 4,
            Keys::KEY_4 => 5,
            Keys::KEY_5 => 6,
            Keys::KEY_6 => 7,
            Keys::KEY_7 => 8,
            Keys::KEY_8 => 9,
            Keys::KEY_9 => 10,
            Keys::KEY_0 => 11,
            Keys::KEY_MINUS => 12,
            Keys::KEY_EQUAL => 13,
            Keys::KEY_BACKSPACE => 14,
            Keys::KEY_TAB => 15,
            Keys::KEY_Q => 16,
            Keys::KEY_W => 17,
            Keys::KEY_E => 18,
            Keys::KEY_R => 19,
            Keys::KEY_T => 20,
            Keys::KEY_Y => 21,
            Keys::KEY_U => 22,
            Keys::KEY_I => 23,
            Keys::KEY_O => 24,
            Keys::KEY_P => 25,
            Keys::KEY_LEFTBRACE => 26,
            Keys::KEY_RIGHTBRACE => 27,
            Keys::KEY_ENTER => 28,
            Keys::KEY_LEFTCTRL => 29,
            Keys::KEY_A => 30,
            Keys::KEY_S => 31,
            Keys::KEY_D => 32,
            Keys::KEY_F => 33,
            Keys::KEY_G => 34,
            Keys::KEY_H => 35,
            Keys::KEY_J => 36,
            Keys::KEY_K => 37,
            Keys::KEY_L => 38,
            Keys::KEY_SEMICOLON => 39,
            Keys::KEY_APOSTROPHE => 40,
            Keys::KEY_GRAVE => 41,
            Keys::KEY_LEFTSHIFT => 42,
            Keys::KEY_BACKSLASH => 43,
            Keys::KEY_Z => 44,
            Keys::KEY_X => 45,
            Keys::KEY_C => 46,
            Keys::KEY_V => 47,
            Keys::KEY_B => 48,
            Keys::KEY_N => 49,
            Keys::KEY_M => 50,
            Keys::KEY_COMMA => 51,
            Keys::KEY_DOT => 52,
            Keys::KEY_SLASH => 53,
            Keys::KEY_RIGHTSHIFT => 54,
            Keys::KEY_KPASTERISK => 55,
            Keys::KEY_LEFTALT => 56,
            Keys::KEY_SPACE => 57,
            Keys::KEY_CAPSLOCK => 58,
            Keys::KEY_F1 => 59,
            Keys::KEY_F2 => 60,
            Keys::KEY_F3 => 61,
            Keys::KEY_F4 => 62,
            Keys::KEY_F5 => 63,
            Keys::KEY_F6 => 64,
            Keys::KEY_F7 => 65,
            Keys::KEY_F8 => 66,
            Keys::KEY_F9 => 67,
            Keys::KEY_F10 => 68,
            Keys::KEY_NUMLOCK => 69,
            Keys::KEY_SCROLLLOCK => 70,
            Keys::KEY_KP7 => 71,
            Keys::KEY_KP8 => 72,
            Keys::KEY_KP9 => 73,
            Keys::KEY_KPMINUS => 74,
            Keys::KEY_KP4 => 75,
            Keys::KEY_KP5 => 76,
            Keys::KEY_KP6 => 77,
            Keys::KEY_KPPLUS => 78,
            Keys::KEY_KP1 => 79,
            Keys::KEY_KP2 => 80,
            Keys::KEY_KP3 => 81,
            Keys::KEY_KP0 => 82,
            Keys::KEY_KPDOT => 83,
            Keys::KEY_ZENKAKUHANKAKU => 85,
            Keys::KEY_102ND => 86,
            Keys::KEY_F11 => 87,
            Keys::KEY_F12 => 88,
            Keys::KEY_RO => 89,
            Keys::KEY_KATAKANA => 90,
            Keys::KEY_HIRAGANA => 91,
            Keys::KEY_HENKAN => 92,
            Keys::KEY_KATAKANAHIRAGANA => 93,
            Keys::KEY_MUHENKAN => 94,
            Keys::KEY_KPJPCOMMA => 95,
            Keys::KEY_KPENTER => 96,
            Keys::KEY_RIGHTCTRL => 97,
            Keys::KEY_KPSLASH => 98,
            Keys::KEY_SYSRQ => 99,
            Keys::KEY_RIGHTALT => 100,
            Keys::KEY_LINEFEED => 101,
            Keys::KEY_HOME => 102,
            Keys::KEY_UP => 103,
            Keys::KEY_PAGEUP => 104,
            Keys::KEY_LEFT => 105,
            Keys::KEY_RIGHT => 106,
            Keys::KEY_END => 107,
            Keys::KEY_DOWN => 108,
            Keys::KEY_PAGEDOWN => 109,
            Keys::KEY_INSERT => 110,
            Keys::KEY_DELETE => 111,
            Keys::KEY_MACRO => 112,
            Keys::KEY_MUTE => 113,
            Keys::KEY_VOLUMEDOWN => 114,
            Keys::KEY_VOLUMEUP => 115,
            Keys::KEY_POWER => 116,
            Keys::KEY_KPEQUAL => 117,
            Keys::KEY_KPPLUSMINUS => 118,
            Keys::KEY_PAUSE => 119,
            Keys::KEY_SCALE => 120,
            Keys::KEY_KPCOMMA => 121,
            Keys::KEY_HANGEUL => 122,
            Keys::KEY_HANJA => 123,
            Keys::KEY_YEN => 124,
            Keys::KEY_LEFTMETA => 125,
            Keys::KEY_RIGHTMETA => 126,
            Keys::KEY_COMPOSE => 127,
            Keys::KEY_STOP => 128,
            Keys::KEY_AGAIN => 129,
            Keys::KEY_PROPS => 130,
            Keys::KEY_UNDO => 131,
            Keys::KEY_FRONT => 132,
            Keys::KEY_COPY => 133,
            Keys::KEY_OPEN => 134,
            Keys::KEY_PASTE => 135,
            Keys::KEY_FIND => 136,
            Keys::KEY_CUT => 137,
            Keys::KEY_HELP => 138,
            Keys::KEY_MENU => 139,
            Keys::KEY_CALC => 140,
            Keys::KEY_SETUP => 141,
            Keys::KEY_SLEEP => 142,
            Keys::KEY_WAKEUP => 143,
            Keys::KEY_FILE => 144,
            Keys::KEY_SENDFILE => 145,
            Keys::KEY_DELETEFILE => 146,
            Keys::KEY_XFER => 147,
            Keys::KEY_PROG1 => 148,
            Keys::KEY_PROG2 => 149,
            Keys::KEY_WWW => 150,
            Keys::KEY_MSDOS => 151,
            Keys::KEY_COFFEE => 152,
            Keys::KEY_SCREENLOCK => 152,
            Keys::KEY_ROTATE_DISPLAY => 153,
            Keys::KEY_DIRECTION => 153,
            Keys::KEY_CYCLEWINDOWS => 154,
            Keys::KEY_MAIL => 155,
            Keys::KEY_BOOKMARKS => 156,
            Keys::KEY_COMPUTER => 157,
            Keys::KEY_BACK => 158,
            Keys::KEY_FORWARD => 159,
            Keys::KEY_CLOSECD => 160,
            Keys::KEY_EJECTCD => 161,
            Keys::KEY_EJECTCLOSECD => 162,
            Keys::KEY_NEXTSONG => 163,
            Keys::KEY_PLAYPAUSE => 164,
            Keys::KEY_PREVIOUSSONG => 165,
            Keys::KEY_STOPCD => 166,
            Keys::KEY_RECORD => 167,
            Keys::KEY_REWIND => 168,
            Keys::KEY_PHONE => 169,
            Keys::KEY_ISO => 170,
            Keys::KEY_CONFIG => 171,
            Keys::KEY_HOMEPAGE => 172,
            Keys::KEY_REFRESH => 173,
            Keys::KEY_EXIT => 174,
            Keys::KEY_MOVE => 175,
            Keys::KEY_EDIT => 176,
            Keys::KEY_SCROLLUP => 177,
            Keys::KEY_SCROLLDOWN => 178,
            Keys::KEY_KPLEFTPAREN => 179,
            Keys::KEY_KPRIGHTPAREN => 180,
            Keys::KEY_NEW => 181,
            Keys::KEY_REDO => 182,
            Keys::KEY_F13 => 183,
            Keys::KEY_F14 => 184,
            Keys::KEY_F15 => 185,
            Keys::KEY_F16 => 186,
            Keys::KEY_F17 => 187,
            Keys::KEY_F18 => 188,
            Keys::KEY_F19 => 189,
            Keys::KEY_F20 => 190,
            Keys::KEY_F21 => 191,
            Keys::KEY_F22 => 192,
            Keys::KEY_F23 => 193,
            Keys::KEY_F24 => 194,
            Keys::KEY_PLAYCD => 200,
            Keys::KEY_PAUSECD => 201,
            Keys::KEY_PROG3 => 202,
            Keys::KEY_PROG4 => 203,
            Keys::KEY_DASHBOARD => 204,
            Keys::KEY_SUSPEND => 205,
            Keys::KEY_CLOSE => 206,
            Keys::KEY_PLAY => 207,
            Keys::KEY_FASTFORWARD => 208,
            Keys::KEY_BASSBOOST => 209,
            Keys::KEY_PRINT => 210,
            Keys::KEY_HP => 211,
            Keys::KEY_CAMERA => 212,
            Keys::KEY_SOUND => 213,
            Keys::KEY_QUESTION => 214,
            Keys::KEY_EMAIL => 215,
            Keys::KEY_CHAT => 216,
            Keys::KEY_SEARCH => 217,
            Keys::KEY_CONNECT => 218,
            Keys::KEY_FINANCE => 219,
            Keys::KEY_SPORT => 220,
            Keys::KEY_SHOP => 221,
            Keys::KEY_ALTERASE => 222,
            Keys::KEY_CANCEL => 223,
            Keys::KEY_BRIGHTNESSDOWN => 224,
            Keys::KEY_BRIGHTNESSUP => 225,
            Keys::KEY_MEDIA => 226,
            Keys::KEY_SWITCHVIDEOMODE => 227,
            Keys::KEY_KBDILLUMTOGGLE => 228,
            Keys::KEY_KBDILLUMDOWN => 229,
            Keys::KEY_KBDILLUMUP => 230,
            Keys::KEY_SEND => 231,
            Keys::KEY_REPLY => 232,
            Keys::KEY_FORWARDMAIL => 233,
            Keys::KEY_SAVE => 234,
            Keys::KEY_DOCUMENTS => 235,
            Keys::KEY_BATTERY => 236,
            Keys::KEY_BLUETOOTH => 237,
            Keys::KEY_WLAN => 238,
            Keys::KEY_UWB => 239,
            Keys::KEY_VIDEO_NEXT => 241,
            Keys::KEY_VIDEO_PREV => 242,
            Keys::KEY_BRIGHTNESS_CYCLE => 243,
            Keys::KEY_BRIGHTNESS_AUTO => 244,
            Keys::KEY_BRIGHTNESS_ZERO => 244,
            Keys::KEY_DISPLAY_OFF => 245,
            Keys::KEY_WWAN => 246,
            Keys::KEY_WIMAX => 246,
            Keys::KEY_RFKILL => 247,
            Keys::KEY_MICMUTE => 248
        }
    }
}